name: destroy-ephemeral-resources
run-name: "Destroying ephemeral resources"
on:
  schedule:
    - cron: "0 05 * * *"  # Every 5AM UTC Mon-Fri
    - cron: "00 12 * * 1,2,3,4,5"  # Every weekday at 12PM CT
  
  workflow_dispatch:
    inputs:
      role_to_assume:
        description: "Role to assume in AWS"
        default: arn:aws:iam::014630368052:role/gh-actions-role
        type: string

env: 
  AWS_REGION: us-east-1

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  destroy-k8s-deployments:
    strategy:      
      matrix:
        environment: ["dev"]    # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#handling-failures
    uses: ./.github/workflows/terraform.yml
    with:
      apply: true
      destroy: true
      k8s-deploy: true
      fmt-check: false
      workspace: ${{ matrix.environment }}
      working-dir: infrastructure/ephemeral-resources/k8s-deployments
      role-to-assume: arn:aws:iam::014630368052:role/gh-actions-role

  destroy-ephemeral-resources:
    needs: destroy-k8s-deployments
    strategy:
      matrix:
        environment: ["dev"]
    uses: ./.github/workflows/terraform.yml
    with:
      apply: true
      destroy: true
      fmt-check: false
      workspace: ${{ matrix.environment }}
      working-dir: infrastructure/ephemeral-resources/
      role-to-assume: arn:aws:iam::014630368052:role/gh-actions-role
